// cochise.py
// analysis/
//     analyze-create-tables.py
//     common_analysis.py
//     create-graphs.py
//     create-mitre-stats.py
//     create-overview-table.py
//     create-tool-analysis-errors.py
//     create-tool-analysis.py
//     index_duration.py
//     index_rounds_and_tokens.py
//     index_rounds.py
//     show_tokens.py
//     static-graphs.py
// summarizers/
//     agent_analzyer.py
//     initial_analyzer.py
// templates/
//     executor_prompt.md.jinja2
//     ptt_next.md.jinja2
//     ptt_update.md.jinja2
//     scenario.md
// analyze-json-graphs.py
// analyze-json-logs.py
// cochise-replay.py
// common.py
// executor.py
// fabric_ssh.py
// kalissh.py
// logger.py
// ptt.py
// wintermute.py